Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/Documentation:
  Enabled: false
