Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/DotPosition:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
